name: Publish Docker image
on:
  push:
    branches:
      - master
      - feature/publish-container-image-using-github-actions

#  release:
#    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: senbot
          password: ${{ secrets.SENBOT_CR_PAT }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tag_with_ref: true
        env:
          DOCKER_BUILDKIT: 1

